language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO=1.7.4
  - DJANGO=1.6.10
  - DJANGO=1.5.12
  - DJANGO=1.4.19

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4.10

install:
  - pip install Django==$DJANGO times
  - pip install da-vinci
  - pip install pillow
  - pip install redis
  - sudo apt-get install -qq optipng

script: make test
services: redis
